# Generated by Django 5.0.1 on 2024-01-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_version_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='is_active',
        ),
        migrations.AddField(
            model_name='version',
            name='active_version',
            field=models.BooleanField(choices=[(True, 'Активно'), (False, 'Неактивно')], default=False, verbose_name='Статус'),
        ),
    ]
